<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-30 at 06:30:18.
 */
class DateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = (object) array(
			'type' => 'date',
			'null' => false
		);
    }

	public function providerPass()
	{
		return array(
			array(strtotime('Jan 1, 101')),
			array(strtotime('12/31/2999')),
			array(time()),
			array(strtotime('Feb 29, 2033'))
		);
	}

	public function providerTransformIn()
	{

	}

	public function providerTransformOut()
	{

	}

    /**
     * @covers Gacela\Field\Date::validate
	 * @dataProvider providerPass
     */
    public function testValidatePass($time)
    {
        $this->assertTrue(Date::validate($this->object, $time));
    }

	/**
	 * @covers Gacela\Field\Date::validate
	 */
	public function testValidatePassNull()
	{
		$this->object->null = true;

		$this->assertTrue(Date::validate($this->object, null));
	}

	/**
     * @covers Gacela\Field\Date::transform
     */
    public function testTransformIn($expected, $val)
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

	public function testTransformOut($expected, $val)
	{

	}
}
