<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 05:16:46.
 */
class DecimalTest extends \PHPUnit_Framework_TestCase
{
	protected $meta = null;

	protected function setUp()
	{
		$this->meta = (object) array(
			'type' => 'decimal',
			'length' => 15,
			'scale' => 5,
			'null' => false
		);
	}

	public function providerTransform()
	{

	}

	public function testValidateNullCode()
	{
		$this->assertEquals(
			Decimal::NULL_CODE,
			Decimal::validate(
				$this->meta,
				null
			)
		);
	}

	public function testValidateLengthCode()
	{
		$this->assertEquals(Decimal::LENGTH_CODE, Decimal::validate($this->meta, 1234));
	}

	/**
	 * @param $value
	 * @dataProvider providerTypeCode
	 */
	public function testValidateTypeCode($value)
	{
		$this->assertEquals(Decimal::TYPE_CODE, Decimal::validate($this->meta, $value));
	}

    /**
     * @covers Gacela\Field\Decimal::validate
     * @dataProvider providerPass
     */
    public function testValidatePassDecimals($value)
    {
		$this->assertTrue(Decimal::validate($this->meta, $value));
    }

	public function testValidatePassNull()
	{
		$this->meta->null = true;

		$this->assertTrue(Decimal::validate($this->meta, null));
	}

    /**
     * @covers Gacela\Field\Decimal::transform
     * @dataProvider providerTransform
     */
    public function testTransform($provided, $expected)
    {
		$this->assertEquals($expected, Decimal::transform($this->meta, $provided));
    }
}
