<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-30 at 06:30:30.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Enum
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = (object) array(
			'type' => 'enum',
			'values' => array('one', 2, 'three', 4),
			'null' => false
		);
    }

    /**
     * @covers Gacela\Field\Enum::validate
     * @todo   Implement testValidate().
     */
    public function testValidateValueCode()
    {
        $this->assertEquals(Enum::VALUE_CODE, Enum::validate($this->object, 'four'));
    }

	public function testValidateNullCode()
	{
		$this->assertEquals(Enum::NULL_CODE, Enum::validate($this->object, null));
	}

	public function testValidatePass()
	{
		$this->assertTrue(Enum::validate($this->object, 'one'));
	}

	public function testValidatePassNull()
	{
		$this->object->null = true;

		$this->assertTrue(Enum::validate($this->object, null));
	}

    /**
     * @covers Gacela\Field\Enum::transform
     */
    public function testTransformIn()
    {
        $this->assertEquals(2, Enum::transform($this->object, 2, true));
    }

	/**
	 * @covers Gacela\Field\Enum::transform
	 */
	public function testTransformOut()
	{
		$this->assertEquals('three', Enum::transform($this->object, 'three', false));
	}
}
