<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-30 at 06:30:30.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \stdClass
     */
    protected $meta;

	/**
	 * @var Enum
	 */
	protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Enum;

        $this->meta = (object) array(
			'type' => 'enum',
			'values' => array('one', 2, 'three', 4),
			'null' => false
		);
    }

    /**
     * @covers Gacela\Field\Enum::validate
     * @todo   Implement testValidate().
     */
    public function testValidateValueCode()
    {
        $this->assertEquals(Enum::VALUE_CODE, $this->object->validate($this->meta, 'four'));
    }

	public function testValidateNullCode()
	{
		$this->assertEquals(Enum::NULL_CODE, $this->object->validate($this->meta, null));
	}

	public function testValidatePass()
	{
		$this->assertTrue($this->object->validate($this->meta, 'one'));
	}

	public function testValidatePassNull()
	{
		$this->meta->null = true;

		$this->assertTrue($this->object->validate($this->meta, null));
	}

    /**
     * @covers Gacela\Field\Enum::transform
     */
    public function testTransformIn()
    {
        $this->assertSame(2, $this->object->transform($this->meta, 2, true));
    }

	/**
	 * @covers Gacela\Field\Enum::transform
	 */
	public function testTransformOut()
	{
		$this->assertSame('three', $this->object->transform($this->meta, 'three', false));
	}
}
