<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-20 at 16:50:12.
 */
class FieldTest extends \PHPUnit_Framework_TestCase
{
	public function testNullCode()
	{
		$this->assertEquals('null', Field::NULL_CODE);
	}

	public function testLengthCode()
	{
		$this->assertEquals('invalid_length', Field::LENGTH_CODE);
	}
}
