<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 05:03:23.
 */
class FloatTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Float
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = (object) array(
			'type' => 'float',
			'length' => 12,
			'null' => false
		);
    }

	public function providerTransform()
	{
		return array(
			array(12.34, 12.34),
			array('1', 1),
			array("1234.12345", 1234.12345),
			array(1234567.1234)
		);
	}

	public function providerTypeCode()
	{
		return array(
			array('String'),
			array(1),
			array(array()),
			array(new \stdClass())
		);
	}

	public function testValidatePassNull()
	{
		$this->object->null = true;

		$this->assertTrue(Float::validate($this->object, null));
	}

    /**
     * @covers Gacela\Field\Float::validate
     * @dataProvider providerTypeCode
     */
    public function testValidateTypeCode($value)
    {
        $this->assertEquals(Float::TYPE_CODE, Float::validate($this->object, $value));
    }

	public function testValidateNullCode()
	{
		$this->assertEquals(Float::NULL_CODE, Float::validate($this->object, null));
	}

    /**
     * @covers Gacela\Field\Float::transform
     * @todo   Implement testTransform().
     */
    public function testTransform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
