<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-26 at 05:03:23.
 */
class FloatTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \stdClass
     */
    protected $meta;

	/**
	 * @var Float
	 */
	protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$this->object = new Float;

        $this->meta = (object) array(
			'type' => 'float',
			'length' => 12,
			'null' => false
		);
    }

	public function providerTransform()
	{
		return array(
			array(12.34, 12.34),
			array('1', 1.0),
			array("1234.12345", 1234.12345),
			array(1234567.1234, 1234567.1234),
			array(false, null),
			array('', null),
		);
	}

	public function providerTypeCode()
	{
		return array(
			array('String'),
			array(1),
			array(array()),
			array(new \stdClass())
		);
	}

	public function testValidatePassNull()
	{
		$this->meta->null = true;

		$this->assertTrue($this->object->validate($this->meta, null));
	}

    /**
     * @covers Gacela\Field\Float::validate
     * @dataProvider providerTypeCode
     */
    public function testValidateTypeCode($value)
    {
        $this->assertEquals(Float::TYPE_CODE, $this->object->validate($this->meta, $value));
    }

	public function testValidateNullCode()
	{
		$this->assertEquals(Float::NULL_CODE, $this->object->validate($this->meta, null));
	}

    /**
     * @covers Gacela\Field\Float::transform
     * @dataProvider providerTransform
     */
    public function testTransform($in, $expected)
    {
		$this->assertSame($expected, $this->object->transform($this->meta, $in));
    }
}
