<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-29 at 20:14:17.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{

	protected $object;

	protected function setUp()
	{
		$this->object = (object) array(
			'type' => 'string',
			'length' => 10,
			'null' => false
		);
	}

    /**
     * @covers Gacela\Field\String::validate
     * @todo   Implement testValidate().
     */
    public function testValidateNull()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

	public function testValidateLength()
	{
		$this->markTestIncomplete();
	}

    /**
     * @covers Gacela\Field\String::transform
     * @todo   Implement testTransform().
     */
    public function testTransform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
