<?php
namespace Gacela\Field;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-29 at 20:14:17.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{

	protected $meta;

	/**
	 * @var String
	 */
	protected $object;

	protected function setUp()
	{
		$this->object = new String;

		$this->meta = (object) array(
			'type' => 'string',
			'length' => 10,
			'null' => false
		);
	}

    /**
     * @covers Gacela\Field\String::validate
     */
    public function testValidateNullCode()
    {
		$this->assertEquals(String::NULL_CODE, $this->object->validate($this->meta, null));
    }

	public function testValidateLengthCode()
	{
		$this->assertEquals(String::LENGTH_CODE, $this->object->validate($this->meta, 'This is a string longer than 10 characters.'));
	}

	public function testValidatePass()
	{
		$this->assertTrue($this->object->validate($this->meta, 'I am short'));
	}

	public function testValidatePassNull()
	{
		$this->meta->null = true;

		$this->assertTrue($this->object->validate($this->meta, null));
	}

    /**
     * @covers Gacela\Field\String::transform
     */
    public function testTransformIn()
    {
		$string = 'I am a very fine string';

        $this->assertSame($string, $this->object->transform($this->meta, $string, true));
    }

	public function testTransformOut()
	{
		$string = 'New String';

		$this->assertSame($string, $this->object->transform($this->meta, $string, false));
	}
}
