<?php
namespace Gacela\DataSource\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-22 at 16:53:00.
 * @group Gacela
 * @group Gacela.DataSource
 * @group Gacela.DataSource.Adapter
 */
class AdapterTest extends \Test\GUnit\TestCase
{
	/**
	 * @var Adapter
	 */
	protected $object;

	public function setUp()
	{
		$this->object = $this->getMockForAbstractClass(
			'Gacela\DataSource\Adapter\Adapter',
			array(
				\Gacela::instance(),
				array(
					'type' => 'mysql',
					'schema' => 'test',
					'username' => 'gacela',
					'password' => 'gacela',
					'host' => 'localhost'
				)
			)
		);
	}

	/**
	 * @expectedException ReflectionException
	 */
	public function test__callWithoutLoadedConnection()
	{
		$this->assertSame(3, $this->object->fakeMethod());
	}
}

