DROP PROCEDURE IF EXISTS sp_belongs_to;
DROP PROCEDURE IF EXISTS sp_has_many;

DELIMITER //

CREATE PROCEDURE sp_belongs_to (IN schemaName VARCHAR(100), IN tableName VARCHAR(100))
	BEGIN
		SELECT COLUMN_NAME AS keyColumn, REFERENCED_TABLE_NAME AS referencedTable, REFERENCED_COLUMN_NAME AS referencedColumn
		FROM INFORMATION_SCHEMA.key_column_usage
		WHERE TABLE_SCHEMA = schemaName
		AND TABLE_NAME = tableName
		AND REFERENCED_TABLE_NAME IS NOT NULL
		AND `COLUMN_NAME` = REFERENCED_COLUMN_NAME;
	END //

CREATE PROCEDURE sp_has_many (IN schemaName VARCHAR(100), IN tableName VARCHAR(100))
	BEGIN
		SELECT REFERENCED_COLUMN_NAME AS keyColumn, TABLE_NAME AS referencedTable, COLUMN_NAME AS referencedColumn
		FROM INFORMATION_SCHEMA.key_column_usage
		WHERE TABLE_SCHEMA = schemaName
		AND REFERENCED_TABLE_NAME = tableName
		AND `COLUMN_NAME` = REFERENCED_COLUMN_NAME;
	END //

DELIMITER ;
