DROP PROCEDURE IF EXISTS sp_belongs_to;
DROP PROCEDURE IF EXISTS sp_has_many;

DELIMITER //

CREATE PROCEDURE sp_belongs_to (IN schemaName VARCHAR(100), IN tableName VARCHAR(100))
	BEGIN
		SELECT COLUMN_NAME AS keyColumn, REFERENCED_TABLE_NAME AS refTable, REFERENCED_COLUMN_NAME AS refColumn, CONSTRAINT_NAME AS constraintName
		FROM INFORMATION_SCHEMA.key_column_usage
		WHERE TABLE_SCHEMA = schemaName
		AND TABLE_NAME = tableName
		AND REFERENCED_TABLE_NAME IS NOT NULL;
	END //

CREATE PROCEDURE sp_has_many (IN schemaName VARCHAR(100), IN tableName VARCHAR(100))
	BEGIN
		SELECT REFERENCED_COLUMN_NAME AS keyColumn, TABLE_NAME AS refTable, COLUMN_NAME AS refColumn, CONSTRAINT_NAME AS constraintName
		FROM INFORMATION_SCHEMA.key_column_usage
		WHERE TABLE_SCHEMA = schemaName
		AND REFERENCED_TABLE_NAME = tableName;
	END //

DELIMITER ;
