<?php
namespace Gacela\DataSource\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-18 at 09:05:30.
 */
class SqlTest extends \Test\TestCase
{
    /**
     * @var Sql
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sql;
    }

	public function providerDates()
	{
		return array(
			array('2013-03-27', '2013-03-27'),
			array('1983-03-27T06:05:00-07:00', '1983-03-27 06:05:00')			
		);	
	}

    /**
     * @covers Gacela\DataSource\Query\Sql::bind
	 * @dataProvider providerDates
	 */
    public function testBindISO8601DateValue($date, $bound)
	{
		$time = time();

		$this->object->where('date = :date', array(':date' => $date));

		$where = $this->object->where;
		
		list($sql, $binds) = $this->object->assemble();

		$this->assertSame($bound, $binds[':date']);
    }

}
